/*
 * * init_n_cfg.c
 *
 *  Created on: Dec 23, 2025
 *      Author: anish
 */

#include <stdio.h>
#include "init_n_cfg.h"

SPIHandle_st SPI1_Handle;
GPIOHandle_st SPI1_SCK;
GPIOHandle_st SPI1_MISO;
GPIOHandle_st SPI1_MOSI;
GPIOHandle_st SPI1_Gyro1_CS;

Gyro1Handle_st Gyro1_Handle;

GPIOHandle_st DiscoBoard_LD3;
GPIOHandle_st DiscoBoard_LD4;
GPIOHandle_st PushButton_Inp;

void init_stm32clksys()
{
	STM32_RCC_CR_Cfg RCC_CR_CFG = {0};
	STM32_RCC_CFGR_Cfg RCC_CFGR_CFG = {0};
	STM32_RCC_AHBENR_Cfg RCC_AHBENR_CFG = {0};
	STM32_RCC_APB2ENR_Cfg RCC_APB2ENR_CFG = {0};
	STM32_RCC_APB1ENR_Cfg RCC_APB1ENR_CFG = {0};

	RCC_CR_CFG.RTCPRE = RTCPRE_VAL;
	RCC_CR_CFG.CSSON = CSS_ENABLE;
	RCC_CR_CFG.PLLON = PLL_ENABLE;
	RCC_CR_CFG.HSEBYP = HSEBYP_ENABLE;
	RCC_CR_CFG.HSEON = HSE_ENABLE;
	RCC_CR_CFG.MSION = MSI_ENABLE;
	RCC_CR_CFG.HSION = HSI_ENABLE;

	RCC_CFGR_CFG.MCOPRE = MCOPRE_VAL;
	RCC_CFGR_CFG.MCOSEL = MCOSEL_VAL;
	RCC_CFGR_CFG.PLLDIV = PLLDIV_VAL;
	RCC_CFGR_CFG.PLLMUL = PLLMUL_IND;
	RCC_CFGR_CFG.PLLSRC = PLLSRC_VAL;
	RCC_CFGR_CFG.PPRE2 = PPRE2_IND;
	RCC_CFGR_CFG.PPRE1 = PPRE1_IND;
	RCC_CFGR_CFG.HPRE = HPRE_IND;
	RCC_CFGR_CFG.SW = SW_VAL;

	RCC_AHBENR_CFG.FSMCEN = FSMC_ENABLE;
	RCC_AHBENR_CFG.AESEN = AES_ENABLE;
	RCC_AHBENR_CFG.DMA2EN = DMA2_ENABLE;
	RCC_AHBENR_CFG.DMA1EN = DMA1_ENABLE;
	RCC_AHBENR_CFG.FLITFEN = FLITF_ENABLE;
	RCC_AHBENR_CFG.CRCEN = CRC_ENABLE;
	RCC_AHBENR_CFG.GPIOGEN = GPIOG_ENABLE;
	RCC_AHBENR_CFG.GPIOFEN = GPIOF_ENABLE;
	RCC_AHBENR_CFG.GPIOHEN = GPIOH_ENABLE;
	RCC_AHBENR_CFG.GPIOEEN = GPIOE_ENABLE;
	RCC_AHBENR_CFG.GPIODEN = GPIOD_ENABLE;
	RCC_AHBENR_CFG.GPIOCEN = GPIOC_ENABLE;
	RCC_AHBENR_CFG.GPIOBEN = GPIOB_ENABLE;
	RCC_AHBENR_CFG.GPIOAEN = GPIOA_ENABLE;

	RCC_APB1ENR_CFG.COMPEN = COMP_ENABLE;
	RCC_APB1ENR_CFG.DACEN = DAC_ENABLE;
	RCC_APB1ENR_CFG.PWREN = PWR_ENABLE;
	RCC_APB1ENR_CFG.USBEN = USB_ENABLE;
	RCC_APB1ENR_CFG.I2C2EN = I2C2_ENABLE;
	RCC_APB1ENR_CFG.I2C1EN = I2C1_ENABLE;
	RCC_APB1ENR_CFG.UART5EN = UART5_ENABLE;
	RCC_APB1ENR_CFG.UART4EN = UART4_ENABLE;
	RCC_APB1ENR_CFG.USART3EN = USART3_ENABLE;
	RCC_APB1ENR_CFG.USART2EN = USART2_ENABLE;
	RCC_APB1ENR_CFG.SPI3EN = SPI3_ENABLE;
	RCC_APB1ENR_CFG.SPI2EN = SPI2_ENABLE;
	RCC_APB1ENR_CFG.WWDEN = WWD_ENABLE;
	RCC_APB1ENR_CFG.LCDEN = LCD_ENABLE;
	RCC_APB1ENR_CFG.TIM7EN = TIM7_ENABLE;
	RCC_APB1ENR_CFG.TIM6EN = TIM6_ENABLE;
	RCC_APB1ENR_CFG.TIM5EN = TIM5_ENABLE;
	RCC_APB1ENR_CFG.TIM4EN = TIM4_ENABLE;
	RCC_APB1ENR_CFG.TIM3EN = TIM3_ENABLE;
	RCC_APB1ENR_CFG.TIM2EN = TIM2_ENABLE;

	RCC_APB2ENR_CFG.USART1EN = USART1_ENABLE;
	RCC_APB2ENR_CFG.SPIEN = SPI1_ENABLE;
	RCC_APB2ENR_CFG.SDIOEN = SDIO_ENABLE;
	RCC_APB2ENR_CFG.ADC1EN = ADC1_ENABLE;
	RCC_APB2ENR_CFG.TIM11EN = TIM11_ENABLE;
	RCC_APB2ENR_CFG.TIM10EN = TIM10_ENABLE;
	RCC_APB2ENR_CFG.TIM9EN = TIM9_ENABLE;
	RCC_APB2ENR_CFG.SYSCFGEN = SYSCFG_ENABLE;

	STM32_ClkSys_Init(&RCC_CR_CFG, &RCC_CFGR_CFG, &RCC_AHBENR_CFG, &RCC_APB1ENR_CFG, &RCC_APB2ENR_CFG);

}

void init_stm32timersys()
{
	BTIMx_Handle_st TS_TIM6_CFG;
	BTIMx_Handle_st TS_TIM7_CFG;

	TS_TIM6_CFG.pBTIMx = pTIM6;
	TS_TIM6_CFG.BTIMx_Cfg.freq = (U16)FREQ_1MS;
	BTIMx_Init(&TS_TIM6_CFG);

	TS_TIM7_CFG.pBTIMx = pTIM7;
	TS_TIM7_CFG.BTIMx_Cfg.freq = (U16)FREQ_10MS;
	BTIMx_Init(&TS_TIM7_CFG);

}


void init_stm32spi()

{
	SPI1_Handle.pSPIX = pSPI1;
	SPI1_Handle.SPI_Cfg.master = TRUE;
	SPI1_Handle.SPI_Cfg.bustype = SPI_BUSTYPE_HDX;
	SPI1_Handle.SPI_Cfg.rxonly = FALSE;
	SPI1_Handle.SPI_Cfg.speed = SPI1_BR;
	SPI1_Handle.SPI_Cfg.dff = FALSE;
	SPI1_Handle.SPI_Cfg.cpha = TRUE;
	SPI1_Handle.SPI_Cfg.cpol = TRUE;
	SPI1_Handle.SPI_Cfg.ssm = FALSE;
	SPI1_Handle.SPI_Cfg.crcen = FALSE;
	SPI_Init(&SPI1_Handle);

	SPI1_SCK.pGPIOX = pGPIOA;
	SPI1_SCK.GPIO_PinCfg.pin = GPIO_PIN_5;
	SPI1_SCK.GPIO_PinCfg.mode = GPIO_MODE_ALTFN;
	SPI1_SCK.GPIO_PinCfg.altfn = 5;
	SPI1_SCK.GPIO_PinCfg.otype = GPIO_OTYPE_PP;
	SPI1_SCK.GPIO_PinCfg.pupd = GPIO_PUPD_NO;
	GPIO_Init(&SPI1_SCK);

	SPI1_MISO.pGPIOX = pGPIOA;
	SPI1_MISO.GPIO_PinCfg.pin = GPIO_PIN_6;
	SPI1_MISO.GPIO_PinCfg.mode = GPIO_MODE_ALTFN;
	SPI1_MISO.GPIO_PinCfg.altfn = 5;
	SPI1_MISO.GPIO_PinCfg.otype = GPIO_PUPD_PD;
	SPI1_MISO.GPIO_PinCfg.pupd = GPIO_PUPD_PD;
	GPIO_Init(&SPI1_MISO);

	SPI1_MOSI.pGPIOX = pGPIOA;
	SPI1_MOSI.GPIO_PinCfg.pin = GPIO_PIN_7;
	SPI1_MOSI.GPIO_PinCfg.mode = GPIO_MODE_ALTFN;
	SPI1_MOSI.GPIO_PinCfg.altfn = 5;
	SPI1_MOSI.GPIO_PinCfg.otype = GPIO_OTYPE_PP;
	SPI1_MOSI.GPIO_PinCfg.pupd = GPIO_PUPD_NO;
	GPIO_Init(&SPI1_MOSI);

}

void init_gyro1()
{
	Gyro1_Handle.pGPIO_Handle = &SPI1_Gyro1_CS;
	Gyro1_Handle.pSPI_Handle = &SPI1_Handle;

	GYRO1_CTRL_REG1 CTRL_REG1;
	GYRO1_CTRL_REG2 CTRL_REG2;
	GYRO1_CTRL_REG3 CTRL_REG3;
	GYRO1_CTRL_REG4 CTRL_REG4;
	GYRO1_CTRL_REG5 CTRL_REG5;

	CTRL_REG1.DR = 0x03;
	CTRL_REG1.BW = 0x03;
	CTRL_REG1.PD = DISABLE;
	CTRL_REG1.Zen = ENABLE;
	CTRL_REG1.Yen = ENABLE;
	CTRL_REG1.Xen = ENABLE;

	CTRL_REG2.HPM = 0x00;
	CTRL_REG2.HPCF = 0x00;

	CTRL_REG3.I1_Int1 = DISABLE;
	CTRL_REG3.I1_Boot = ENABLE;
	CTRL_REG3.H_Lactive = 0;
	CTRL_REG3.PP_OD = 0;
	CTRL_REG3.I2_DRDY = DISABLE;
	CTRL_REG3.I2_WTM = ENABLE;
	CTRL_REG3.I2_ORun = ENABLE;
	CTRL_REG3.I2_Empty = ENABLE;

	CTRL_REG4.BLE = 0x00;
	CTRL_REG4.FS = 0x00;
	CTRL_REG4.ST = 0x00;
	CTRL_REG4.SIM = 0x00;

	CTRL_REG5.BOOT = 0x00;
	CTRL_REG5.FIFO_EN = ENABLE;
	CTRL_REG5.HPen = ENABLE;
	CTRL_REG5.INT_Sel = 0x01;
	CTRL_REG5.Out_Sel = 0x01;

	U8 reg1_w_status = Gyro1_Write(&Gyro1_Handle, GYRO1_CTRL_REG1_ADDR, Gyro1_Pack_CTRL_REG1(&CTRL_REG1));
	U8 reg2_w_status = Gyro1_Write(&Gyro1_Handle, GYRO1_CTRL_REG2_ADDR, Gyro1_Pack_CTRL_REG2(&CTRL_REG2));
	U8 reg3_w_status = Gyro1_Write(&Gyro1_Handle, GYRO1_CTRL_REG3_ADDR, Gyro1_Pack_CTRL_REG3(&CTRL_REG3));
	U8 reg4_w_status = Gyro1_Write(&Gyro1_Handle, GYRO1_CTRL_REG4_ADDR, Gyro1_Pack_CTRL_REG4(&CTRL_REG4));
	U8 reg5_w_status = Gyro1_Write(&Gyro1_Handle, GYRO1_CTRL_REG5_ADDR, Gyro1_Pack_CTRL_REG5(&CTRL_REG5));

	U8 err = !(reg1_w_status & reg2_w_status & reg3_w_status & reg4_w_status & reg5_w_status);

	printf("%d",err);

}

void init_stm32gpio()
{
	PushButton_Inp.pGPIOX = pGPIOA;
	PushButton_Inp.GPIO_PinCfg.pin = GPIO_PIN_0;
	PushButton_Inp.GPIO_PinCfg.mode = GPIO_MODE_INTRE;
	PushButton_Inp.GPIO_PinCfg.otype = GPIO_OTYPE_PP;
	PushButton_Inp.GPIO_PinCfg.pupd = GPIO_PUPD_PD;
	GPIO_Init(&PushButton_Inp);

	DiscoBoard_LD3.pGPIOX = pGPIOB;
	DiscoBoard_LD3.GPIO_PinCfg.pin = GPIO_PIN_7;
	DiscoBoard_LD3.GPIO_PinCfg.mode = GPIO_MODE_OUT;
	DiscoBoard_LD3.GPIO_PinCfg.otype = GPIO_OTYPE_PP;
	DiscoBoard_LD3.GPIO_PinCfg.pupd = GPIO_PUPD_NO;
	GPIO_Init(&DiscoBoard_LD3);

	DiscoBoard_LD4.pGPIOX = pGPIOB;
	DiscoBoard_LD4.GPIO_PinCfg.pin = GPIO_PIN_6;
	DiscoBoard_LD4.GPIO_PinCfg.mode = GPIO_MODE_OUT;
	DiscoBoard_LD4.GPIO_PinCfg.otype = GPIO_OTYPE_PP;
	DiscoBoard_LD4.GPIO_PinCfg.pupd = GPIO_PUPD_NO;
	GPIO_Init(&DiscoBoard_LD4);

}

void IRQ_init()
{
	IRQConfig(IRQ_NO_TIM6, IRQ_NO_TIM6_ENABLE);
	IRQConfig(IRQ_NO_TIM7, IRQ_NO_TIM7_ENABLE);

	IRQConfig(IRQ_NO_EXTI0, IRQ_NO_EXTI0_ENABLE);
	IRQConfig(IRQ_NO_EXTI1, IRQ_NO_EXTI1_ENABLE);
	IRQConfig(IRQ_NO_EXTI2, IRQ_NO_EXTI2_ENABLE);
	IRQConfig(IRQ_NO_EXTI3, IRQ_NO_EXTI3_ENABLE);
	IRQConfig(IRQ_NO_EXTI4, IRQ_NO_EXTI4_ENABLE);
	IRQConfig(IRQ_NO_EXTI9_5, IRQ_NO_EXTI9_5_ENABLE);
	IRQConfig(IRQ_NO_EXTI15_10, IRQ_NO_EXTI15_10_ENABLE);

}
